### PR TITLE
Improve English translations

### PR DESCRIPTION
**Pull request by Raia**
This includes a few small improvements to the English version.

### CODE REVIEW

**Comment by Quandra** [comment]
Thank you :)

**Comment by Raia** [comment]
Thank you :)

Can you update the files in [the release](https://github.com/Quandra/SMHatchingRNGTool/tree/v1.25)?

**Comment by Quandra** [comment]
I released files as v1.25-eng here.
https://github.com/Quandra/SMHatchingRNGTool/releases/tag/v1.25-eng

**Comment by Raia** [comment]
ありがとうございます！

**Pull request merged**
